debug: false

server:
  port: 80
  http2:
    enabled: true

spring:
  resources:
    static-locations: ["classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/", "classpath:/assets/"]
  mvc:
    static-path-pattern: "/assets/**"
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    data-username: root
    data-password: root
  transaction:
    rollback-on-commit-failure: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: xyz.leefly.project.bo
